[build]
  cmd = "go build -o tmp/ezbookkeeping.exe ."
  entrypoint = ["dev.bat"]
  include_ext = ["go", "ini"]
  tmp_dir = "tmp"
  exclude_dir = [
    "tmp", "vendor", "node_modules", "scripts", "docs", ".git", "data", "package",
    "venv", "src", "dist", "public", "storage", "log", "etc", "testdata",
    ".github", ".gitea", ".spec-workflow", ".trae", ".claude", "docker", "skills"
  ]
  delay = 1000
  stop_on_error = true
  log = "build-errors.log"

[env]
  CGO_ENABLED = "1"

[log]
  time = false

[misc]
  clean_on_exit = true
